# Generated by Django 2.0.6 on 2018-06-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalNumber', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('MedicalHistory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem', models.CharField(max_length=255)),
                ('Active', models.BooleanField(default=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pt_list.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='JobStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pt_list.JobStatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pt_list.Patient'),
        ),
    ]
