# Generated by Django 2.0.6 on 2018-06-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientproblem',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Problems', to='pt_list.Patient'),
        ),
    ]
