# Generated by Django 2.0.6 on 2018-07-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_list', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Jobs', to='pt_list.Patient'),
        ),
    ]
