# Generated by Django 2.0.6 on 2018-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_list', '0006_auto_20180701_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='LocationWard',
            field=models.CharField(default='Ash', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientActive',
            field=models.BooleanField(default=True),
        ),
    ]
