# Generated by Django 2.0.6 on 2018-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_list', '0007_auto_20180701_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='FirstName',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(default='M', max_length=2),
            preserve_default=False,
        ),
    ]
