# Generated by Django 2.0.6 on 2018-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_list', '0008_auto_20180701_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobStatus',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='JobStatus',
        ),
    ]
